# See <https://docs.codecov.io/docs/codecovyml-reference>

codecov:
  max_report_age: 24
  require_ci_to_pass: true

coverage:
  precision: 2
  round: nearest
  range: "50...100"
  notify:
    wait_for_ci: true